# Generated by Django 4.0.4 on 2023-02-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('choicee', models.CharField(choices=[('Email', 'Email'), ('Certificate', 'Certificate'), ('Letter', 'Letter')], max_length=200, null=True)),
            ],
        ),
    ]
